# Dependencies
#markdown:            redcarpet
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               JMWY's Tech Blog
tagline:             ''
description:         'Talk is cheap'
url:                 http://JMWY.github.io
baseurl:             /
paginate:            10

# About/contact
author:
  name:              李阳光
  url:               https://twitter.com/jmwy
  email:             jmwy@gmail.com

# Custom vars
version:             2.0

# Social Media
github:				http://github.com/jmwy
twitter:			http://twitter.com/jmwy
disqus:             jmwy

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Rizky Ariestiyansyah
  codename:			Naringu
  link:             https://github.com/ariestiyansyah/naringu

gems: [jekyll-paginate]

comments:
  provider: duoshuo
  duoshuo:
  shot_name: littleworld

